apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          serviceAccountName: backup-ksa
          containers:
          - name: backup
            image: raihhardv/backup
            env:
              - name: URL
                valueFrom:
                  secretKeyRef:
                    name: todoapp
                    key: DATABASE_URL
          restartPolicy: Never # This time we'll run it only once