apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todo-app
          image: raihhardv/todo-app
          env:
            - name: BACKEND_URI
              value: 'http://todo-backend-svc:2345/todos'
            - name: PORT
              value: '3000'
            - name: IMAGE_URI
              value: 'https://loremflickr.com/600/400/landscape'      
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files