apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: raihhardv/todo-backend
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todoapp
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: todoapp
                  key: PORT