apiVersion: ENC[AES256_GCM,data:TVM=,iv:GPmr0xUPxatHt0W74qxMH01vHe1+2Fh1v+QhoWb0hyA=,tag:DxjdsPkt6RG5JETUYCTtmQ==,type:str]
kind: ENC[AES256_GCM,data:H7NtxwZm,iv:dYnlXBR8g7bJAC6p8f4xtM5AumnjjPB7eVDRyU92s3g=,tag:a2hZDd2ql5bW+9yfDIbsjA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oyFz3YYraA==,iv:n1cjfUgtNZqsIyDzEsZSiAhzCvt/6jnJq4aD3bQB4mI=,tag:6HauArgmaJuFXuSJUZa2BA==,type:str]
data:
    BACKEND_URI: ENC[AES256_GCM,data:80/x8byZKYndjSi0SKnDy3pkfE5h4iKLbtrN465h4Oi8kKe/Vcu1r/IURuU=,iv:JxULws//UC5nXtouv3yPEnvNp7Dq+sjkf8t5GtudVog=,tag:hkl3bHkJguYSB0lmJecb3A==,type:str]
    IMAGE_URI: ENC[AES256_GCM,data:gLf32ElwrgZ88b10bqVup1UIVp7niepTAg+xZhUMuf0/SP5sxOnmqqDj1rrcA2n9ARpFhuddEn4=,iv:tOvcg+oMsez1BctQxOpTaqhGruMfwPSfayO1wJrVCJM=,tag:UsqhBwGMmTE977JXZjpjhA==,type:str]
    PORT: ENC[AES256_GCM,data:idkJd8Io85k=,iv:xszesLoTPgHonhsn4HJQFKB0m3eFGceZbVG0W8wNxyU=,tag:j2kBEJqoRO98kPy+iSkCQg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1Mq3Q/9xtX2ThdC3Il1Egw==,iv:SEBeDZDKWzOiPuc1pBUlcvA7dZm8jQSCWxI6zr+imnQ=,tag:i1Re5ODAhabxZ2DvIlELpA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3Ew01LEL3NhgqmhTwtiizLOrRNmavHdz5KEUCAWjUH60cnzdgzOkzjaJ42350UFLjfGHrkjhhAmyOzlADCOOTXKwMqe8tFp0kgyGkCeCNuEUY+WaUklV0wtgrIla6jsWCFHGgw==,iv:glq0KV0Mi+IutafswYN0tR6vXcwyMMviiFzs49rCHfc=,tag:X6n1p2/r+nwPAKaAbMW9TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZkNiNHR0N05ycWVSVHlt
            VStMa3hsSW1qbkNXS29Idkc2ZXBWc2s1clJZCkVRV0R3dXRnZ0lqVU5kbHFvNnZp
            dVJyVkk5dkJCWkFJK0dWVjQ2K0tXTmsKLS0tIHRpVko2S0Z5bVRUQ0kxclFPWHFX
            S3duWkpGZjFSUGRodFRFZk03Z1AyNFEKoDd3FS22w7mu5kwBVAstRWx73BTqVvX+
            D507kJ7NYnTPI5MrETZkVOqJz2Aj/uh6prejaT/yP3S/C3HoToZTYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fn5uxlg6wjvatsxgf9q3vcx65hzfvq4xajx5cl2uhdhrr08jdavqcpnkhv
    lastmodified: "2026-07-02T10:29:58Z"
    mac: ENC[AES256_GCM,data:7vuza5Az3ndtu7cAhpYc3klxH6zKk5rGypIIvY2nt/FpbImTblCgVHauc5pk+8i1NAmc2xBlnVbWTf8diSB92UEVsmy9SC5qUwL5x2KZzHitMLBJY8csoQwWPfqAPJicv+DjYPzHnxSb7QumG5dlII3Y8zV3AGHUviUoRUjKs4U=,iv:LkM9GvNuOl2PQ9qZropYONu+lKKxaGQReewo0LdwO94=,tag:D2puOuJSoq9WjC4gVs01kg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
