apiVersion: ENC[AES256_GCM,data:NJQ=,iv:wtHecjVcmgzoyk6cUurvtIzvkKzLklxfqd4jSeY4s08=,tag:CHei7th/eiz9bnT5dvNZDg==,type:str]
kind: ENC[AES256_GCM,data:XtcYeCH4,iv:TjArEdOwdxQPK+TGDu1H7Z5h2AtLoEAIcb8WqyFbkno=,tag:Ge3PdRl7pFQn/HJIDKehHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hk7N6pfSfw==,iv:TSxi5fqqz9UM3xcf76kfdizo+FlJMkHsz6ZGFDTNCfQ=,tag:W9+JfUIIROYErEIPQRVtaQ==,type:str]
    namespace: ENC[AES256_GCM,data:lzx1D/vQcw==,iv:oPRZEgmuriBJ5mjsbKJEG6SZFT+SrmeG9LlsoLq2ITc=,tag:hR5JdGP6zJ1CiFLBmByxsQ==,type:str]
data:
    BACKEND_URI: ENC[AES256_GCM,data:evvAvjvvBEoNc1Lx809JgguJQpMQ9MwH/r+zU2upMjEFjQBBSJSiMbN/V60=,iv:+4rel/Ptx9hWmvTutStP/BbisAydKkfSllvmNGcnUUQ=,tag:nrse25elveuNiwSLYoW4qg==,type:str]
    IMAGE_URI: ENC[AES256_GCM,data:zwSXWD+wMc6tTjSZHQrYd+jTY9HGvUHISs7ngi+oxubsGCvmMbpD1YZ4n0q30ssGuB26Pk7/B5k=,iv:aE+OlVPA0tCpoiFrM6spnHTQ7iZTBwzJr9a+oj1/X08=,tag:Gb0x0I6IlN1MP6eXJfJqpg==,type:str]
    PORT: ENC[AES256_GCM,data:wEfyPvflsLc=,iv:o1ZicAXfvSEkq8IGi5lgaKBcME3zBSGQAq1IJwvvUz0=,tag:2bPpbknPt5VRu+urlbU/Vw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6DHBeMwcW4omWPrfL416Vw==,iv:7Y7bl1hCqRCI4KYUDHsYtgg/EajFAy0l84c5rQWY2Sk=,tag:PkZGUvqL9IVzjcNnElzkFQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:9hd7Sm6WEEC3uxqrj503Gk5MnTtO/2AZmubIDu0wF/z9bSikPrReKwMXcQ81J7ctG5da6WF7H4sQGR0303Op0zRhqcKn4KqaBCh1Ofp1Yl/3XpNjgJo9wqQ7X2mLbBgxdKZRcw==,iv:IkVfSlrKFz/bTPHxWqJilhohCGfRz03UAkWJ+hOZCXk=,tag:Ubqd+JBMne9xebu2wOL3jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVEhwN2YvcEtpelJVVWdl
            OThuVndRV1pyeWlIWHpxUnJXWE0vR0l2QUFrCnBZL1MzUzZ5WHdmSFJXNThOVEND
            L0FjZ2tzeUxRUGZqOHF6ZTMycUo3bDgKLS0tIEVtaXNOTVNxNmg5QWU0UklIRnlZ
            MUFVR0pMUExHYTh1ME9OdGJaL3pWZkkKSyglI5llHKCkiyMLgM10/z9lFyBIbX7k
            vvo8QaPde6s4zLyvGCWAeRC2PLF/ZD6ebSVpoJjH4QRqaB0hyCaS9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fn5uxlg6wjvatsxgf9q3vcx65hzfvq4xajx5cl2uhdhrr08jdavqcpnkhv
    lastmodified: "2026-07-01T21:18:25Z"
    mac: ENC[AES256_GCM,data:bPBSgS4Jk/exM6+VCWkvQA1yZl/enNDcg+9NX+0WUyrvvLfWsViTl0ipMvQvRe2iJWhinnxjiUIyulJLnA75K0UvwAcMykbhmyn34eDu8+YzyKt1KR7Ap2mLIuoC7+VDSh0VRYbX99WO1Exqp6kA2n367Kc432z7JHzqBirJukE=,iv:qVTsZYHRJ6KY+thoE1HUq8jZydxI6J+llRrYoW++dZE=,tag:IRK/58g6FWE1ssglMQVDcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
