apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikilink
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wikilink
            image: raihhardv/script
          restartPolicy: OnFailure