apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/statefulset.yaml
- ./manifests/deployment-backend.yaml
- ./manifests/deployment-frontend.yaml
- ./manifests/ingress.yaml
#  - ./manifests/backup-cronjob.yaml
images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: fb5a81f10dc27f4545f15c631f838e00483dc6b6
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: fb5a81f10dc27f4545f15c631f838e00483dc6b6
