apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: raihhardv/pingpong@sha256:14cb8adc6c9ec2d033586f812b95d18d5dc72955a99f7dc902ee16fc304f57b2