apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: logoutput-claim
        - name: information
          configMap:
            name: logoutput-configmap
            items:
            - key: "information"
              path: "information.txt"
      containers:
        - name: file-writer
          image: raihhardv/file-writer
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
        - name: file-reader
          image: raihhardv/file-reader@sha256:8512c682025dab655796fc76120a134715a10390de0b3c11adf91fbf4d284d4e
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: message
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
          - name: information
            mountPath: /usr/src/app/config
            readOnly: true
