apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: logoutput-claim
        - name: information
          configMap:
            name: logoutput-configmap
            items:
            - key: "information"
              path: "information.txt"
      containers:
        - name: file-writer
          image: raihhardv/file-writer
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
        - name: file-reader
          image: raihhardv/file-reader@sha256:4baf3ee44f485036b0584253117f3c643800a10ab59883fe17ce87ab650c8c08
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: message
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
          - name: information
            mountPath: /usr/src/app/config
            readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector: 
    app: log-output
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-logoutput
  namespace: exercises
spec:
  parentRefs:
  - name: my-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: log-output-svc
      port: 80