apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/statefulset.yaml
- ./manifests/deployment-pingpong.yaml
- ./manifests/deployment-logoutput.yaml
- ./manifests/persistentvolumeclaim.yaml
- ./manifests/configmap.yaml
- ./manifests/analysistemplate.yaml
- ./manifests/gateway.yaml
- ./manifests/deployment-greeter.yaml
images:
- name: PROJECT/FILE_READER
  newName: raihhardv/file-reader
  newTag: 497b5172484b1884c79480912004c11a51b1a6cc
- name: PROJECT/FILE_WRITER
  newName: raihhardv/file-writer
  newTag: 497b5172484b1884c79480912004c11a51b1a6cc
- name: PROJECT/PINGPONG
  newName: raihhardv/pingpong
  newTag: 497b5172484b1884c79480912004c11a51b1a6cc
