apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-stset
spec:
  serviceName: database-svc
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: database-storage
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: "kubernetes"
        - name: pingpong
          image: raihhardv/pingpong
          env:
            - name: DATABASE_URL
              value: 'postgres://postgres:kubernetes@localhost:5432/postgres?sslmode=disable'
  volumeClaimTemplates:
    - metadata:
        name: database-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi