name: Release application

on:
  push

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: todoapp
  FE_IMAGE: todo-frontend
  BE_IMAGE: todo-backend
  BRANCH: ${{ github.ref_name }}
  AGE_KEY: ${{ secrets.AGE_KEY }}

jobs:
  build-publish-deploy:
    name: Build, Publish, Deploy
    runs-on: ubuntu-latest
    environment: DWK

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: gcloud info
      
      - run: gcloud --quiet auth configure-docker $REGISTRY

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v3'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      
      - name: 'Form the FE image name'
        run: echo "FE_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$FE_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: 'Build Frontend'
        run: docker build --tag $FE_IMAGE_TAG ./the_project/todo-frontend

      - name: 'Publish Frontend'
        run: docker push $FE_IMAGE_TAG
      
      - name: 'Form the BE image name'
        run: echo "BE_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BE_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: 'Build Backend'
        run: docker build --tag $BE_IMAGE_TAG ./the_project/todo-backend

      - name: 'Publish Backend'
        run: docker push $BE_IMAGE_TAG
    
      - name: 'Set up Kustomize'
        uses: imranismail/setup-kustomize@v3
       
      - name: Deploy
        working-directory: ./the_project
        run: |-
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" = "main" ]; then
            NAMESPACE="project"
          else
            NAMESPEACE="$BRANCH_NAME"
          fi

          kubectl create namespace "$NAMESPACE" || true
          kubectl config set-context --current --namespace="$NAMESPACE"
          kustomize edit set namespace "$NAMESPACE"      
          kustomize edit set image todo-frontend=$FE_IMAGE_TAG
          kustomize edit set image todo-backend=$BE_IMAGE_TAG

          cd /manifests

          curl -LO https://github.com/getsops/sops/releases/download/v3.13.2/sops-v3.13.2.linux.amd64
          mv sops-v3.13.2.linux.amd64 /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
          export SOPS_AGE_KEY=$AGE_KEY
          sops --decrypt secret.enc.yaml | kubectl apply -f -

          cd ..

          kustomize build . | kubectl apply -f -

          kubectl rollout status deployment/todo-frontend-dep -n project
          kubectl rollout status deployment/todo-backend-dep -n project
          kubectl get services -n project -o wide